name: Update EPG JSON

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Run converter script
        run: node convert.js

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add output.json

          # evita commit vuoti
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "auto update epg"
          git push
